"""
prompts/templates.py
────────────────────
Markdown report templates for different query types.
"""

from datetime import datetime


def get_company_report_template(company: str, sector: str) -> str:
    return f"""# {company} — Deep Research Analysis
**Sector:** {sector} | **Report Date:** {datetime.now().strftime('%B %d, %Y')}

---

## Executive Summary
> _Key takeaways will appear here_

## Company Overview
- **Founded:** 
- **Headquarters:** 
- **Business Model:** 
- **Key Products/Services:** 

## Financial Performance
| Metric | FY2024 | FY2023 | FY2022 | YoY Change |
|--------|--------|--------|--------|------------|
| Revenue | | | | |
| EBITDA Margin | | | | |
| Net Profit | | | | |
| EPS | | | | |

## Competitive Positioning

## Recent Developments

## Management Commentary

## Risk Factors

## Investment Outlook

---
*Generated by Financial Deep Research Agent*
"""


def get_sector_report_template(sector: str) -> str:
    return f"""# {sector} Sector — Comprehensive Research Report
**Report Date:** {datetime.now().strftime('%B %d, %Y')}

---

## Executive Summary

## Market Overview
- **Market Size:** 
- **Growth Rate (CAGR):** 
- **Key Drivers:** 

## Key Players & Market Share
| Company | Revenue | Market Cap | YoY Growth |
|---------|---------|-----------|------------|

## Trend Analysis

## Regulatory Environment

## Investment Opportunities

## Risk Factors

## Outlook & Projections

---
*Generated by Financial Deep Research Agent*
"""


def get_comparative_report_template(entities: list, sector: str) -> str:
    cols = " | ".join(entities)
    sep = " | ".join(["---"] * len(entities))
    return f"""# Comparative Analysis: {" vs ".join(entities)}
**Sector:** {sector} | **Report Date:** {datetime.now().strftime('%B %d, %Y')}

---

## Executive Summary

## Comparison Overview
| Criteria | {cols} |
|----------|{sep}|
| Revenue | | |
| Market Cap | | |
| EBITDA Margin | | |
| Revenue Growth | | |
| P/E Ratio | | |

## Individual Analysis
{''.join([f"### {e}{chr(10)}{chr(10)}" for e in entities])}

## Head-to-Head Comparison

## Investment Recommendation

---
*Generated by Financial Deep Research Agent*
"""
